Repository kakbutos/MatchThree, pull requests merged in 2023-12, with the labels that each got.

#3 Отображение страниц, используя React Router и React Router DOM
  .editorconfig
  packages/client/.eslintrc.cjs
  packages/client/jest.config.js
  packages/client/package.json
  packages/client/src/app/index.tsx
  packages/client/src/app/providers/router/AppRouter.tsx
  packages/client/src/app/providers/router/RequireAuth.tsx
  packages/client/src/app/providers/router/index.ts
  packages/client/src/app/styles/colors.scss
  packages/client/src/app/styles/index.scss
  packages/client/src/config/.keep
  packages/client/src/config/router/routeConfig.tsx
  packages/client/src/constants/.keep
  packages/client/src/constants/router/router.ts
  packages/client/src/main.tsx
  packages/client/src/pages/.keep
  packages/client/src/pages/login/login.module.scss
  packages/client/src/types/.keep
  packages/client/src/types/router/router.ts
  packages/client/src/widgets/image-layout/image-layout.module.scss
  yarn.lock
Labels: done

#4 Добавил ErrorBoundary, страницу ошибок
  packages/client/__mocks__/jestEmptyComponent.tsx
  packages/client/jest.config.js
  packages/client/package.json
  packages/client/src/app/index.tsx
  packages/client/src/app/providers/error-boundary/ErrorBoundary.tsx
  packages/client/src/assets/icons/star.svg
  packages/client/src/config/router/routeConfig.tsx
  packages/client/src/constants/router/router.ts
  packages/client/src/main.tsx
  packages/client/src/pages/error/ErrorPage.tsx
  packages/client/src/pages/error/error-page.module.scss
  packages/client/src/pages/game/game.module.scss
  packages/client/src/vite-env.d.ts
  packages/client/src/widgets/.keep
  packages/client/vite.config.ts
  yarn.lock
Labels: to review team

#5 COD-17: Добавлен axios. Логика авторизации и AuthGuard
  packages/client/package.json
  packages/client/src/app/providers/router/AppRouter.tsx
  packages/client/src/app/providers/router/RequireAuth.tsx
  packages/client/src/app/styles/colors.scss
  packages/client/src/config/router/routeConfig.tsx
  packages/client/src/constants/router/router.ts
  packages/client/src/hooks/.keep
  packages/client/src/hooks/useApiCall.ts
  packages/client/src/pages/game/Game.tsx
  packages/client/src/pages/login/Login.tsx
  packages/client/src/pages/menu/Menu.tsx
  packages/client/src/pages/menu/index.ts
  packages/client/src/services/.keep
  packages/client/src/services/api/auth/auth-api.ts
  packages/client/src/services/api/auth/types/auth-request.ts
  packages/client/src/services/auth/auth.ts
  packages/client/src/shared/components/spinner/Spinner.tsx
  packages/client/src/shared/components/spinner/spinner.module.scss
  packages/client/src/utils/.keep
  packages/client/src/utils/base-api.ts
  packages/client/src/utils/http-transport.ts
  packages/client/src/widgets/auth-form/AuthForm.tsx
  packages/client/src/widgets/auth-form/auth-form.module.scss
  packages/client/src/widgets/auth-form/index.ts
  packages/client/src/widgets/image-layout/ImageLayout.tsx
  packages/client/src/widgets/image-layout/image-layout.module.scss
  yarn.lock
Labels: to review team, to review praktikum

#7 COD-20: Верстка страницы форума
  packages/client/.eslintrc.cjs
  packages/client/src/assets/icons/arrow-left.svg
  packages/client/src/assets/icons/comment.svg
  packages/client/src/assets/icons/reply.svg
  packages/client/src/assets/images/austronaut-with-laptop.svg
  packages/client/src/assets/images/empty-avatar-man.svg
  packages/client/src/assets/images/forum-title.svg
  packages/client/src/config/router/routeConfig.tsx
  packages/client/src/pages/error/ErrorPage.tsx
  packages/client/src/pages/forum/Forum.tsx
  packages/client/src/pages/forum/forum.module.scss
  packages/client/src/pages/forum/theme-list.mock.ts
  packages/client/src/pages/topic/Topic.tsx
  packages/client/src/pages/topic/comment-list.mock.ts
  packages/client/src/pages/topic/topic.module.scss
  packages/client/src/shared/.keep
  packages/client/src/theme/components/MuiButton.ts
  packages/client/src/theme/components/MuiTextField.ts
  packages/client/src/theme/components/index.ts
  packages/client/src/theme/themeOptions.ts
  packages/client/src/types/comment.ts
  packages/client/src/types/topic.ts
  packages/client/src/widgets/auth-form/AuthForm.tsx
  packages/client/src/widgets/comment-form/CommentForm.tsx
  packages/client/src/widgets/comment-form/comment-form.module.scss
  packages/client/src/widgets/comment/Comment.tsx
  packages/client/src/widgets/comment/comment.module.scss
  packages/client/src/widgets/create-theme-dialog/CreateThemeDialog.tsx
  packages/client/src/widgets/create-theme-dialog/crate-theme-dialog.module.scss
  packages/client/src/widgets/forum-layout/ForumLayout.tsx
  packages/client/src/widgets/forum-layout/forum-layout.module.scss
  packages/client/src/widgets/start/Start.tsx
  packages/client/src/widgets/topic/Topic.tsx
  packages/client/src/widgets/topic/topic.module.scss
Labels: to review team

#11 Страница профиля
  packages/client/src/app/providers/router/AppRouter.tsx
  packages/client/src/config/router/routeConfig.tsx
  packages/client/src/constants/index.ts
  packages/client/src/pages/error/ErrorPage.tsx
  packages/client/src/pages/profile/Profile.tsx
  packages/client/src/services/api/auth/auth-api.ts
  packages/client/src/services/api/user/user-api.ts
  packages/client/src/shared/form-fields/FormInputText.tsx
  packages/client/src/shared/spinner/Spinner.tsx
  packages/client/src/shared/spinner/spinner.module.scss
  packages/client/src/types/auth-request.ts
  packages/client/src/types/auth/auth.ts
  packages/client/src/types/user.ts
  packages/client/src/utils/api/base-api.ts
  packages/client/src/utils/api/http-transport.ts
  packages/client/src/widgets/auth-form/AuthForm.tsx
  packages/client/src/widgets/avatar-from/AvatarForm.tsx
  packages/client/src/widgets/avatar-from/avatar-form.module.scss
  packages/client/src/widgets/password-form/PasswordForm.tsx
  packages/client/src/widgets/profile-form/ProfileForm.tsx
  packages/client/src/widgets/registration-form/RegistrationForm.tsx
Labels: to review praktikum

#13 Добавление игрового движка
  packages/client/src/pages/game/Game.tsx
  packages/client/src/widgets/game-window/ConsoleMessage.tsx
  packages/client/src/widgets/game-window/GameWindow.tsx
  packages/client/src/widgets/game-window/game-window.module.scss
  packages/client/src/widgets/game-window/lib/ConsoleController.ts
  packages/client/src/widgets/game-window/lib/GameEngine.ts
  packages/client/src/widgets/game-window/lib/cluster.ts
  packages/client/src/widgets/game-window/lib/level-settings.ts
  packages/client/src/widgets/game-window/lib/move.ts
  packages/client/src/widgets/game-window/lib/position.ts
  packages/client/src/widgets/game-window/lib/selected-tile.ts
  packages/client/src/widgets/game-window/types/animationstates.enum.ts
  packages/client/src/widgets/game-window/types/gamestates.enum.ts
  packages/client/src/widgets/game-window/types/message-types.enum.ts
  packages/client/src/widgets/game-window/types/tiles-themes.ts
Labels: to review team, to review praktikum

#14 COD-47: Добавление redux. Изменение логики authGuard.
  packages/client/.eslintrc.cjs
  packages/client/package.json
  packages/client/src/app/providers/router/AppRouter.tsx
  packages/client/src/app/providers/router/RequireAuth.tsx
  packages/client/src/hooks/useApiCall.ts
  packages/client/src/hooks/useAppDispatch.ts
  packages/client/src/hooks/useAppSelector.ts
  packages/client/src/main.tsx
  packages/client/src/pages/forum/Forum.tsx
  packages/client/src/pages/profile/Profile.tsx
  packages/client/src/pages/topic/comment-list.mock.ts
  packages/client/src/services/api/auth/auth-api.ts
  packages/client/src/services/api/user/user-api.ts
  packages/client/src/services/auth/auth.ts
  packages/client/src/store/.keep
  packages/client/src/store/index.ts
  packages/client/src/store/user/index.ts
  packages/client/src/store/user/selectors.ts
  packages/client/src/store/user/slice.ts
  packages/client/src/types/auth/auth.ts
  packages/client/src/types/forum/comment.ts
  packages/client/src/types/forum/topic.ts
  packages/client/src/types/loading-status.ts
  packages/client/src/types/user.ts
  packages/client/src/widgets/auth-form/AuthForm.tsx
  packages/client/src/widgets/avatar-from/AvatarForm.tsx
  packages/client/src/widgets/comment/Comment.tsx
  packages/client/src/widgets/main/navbar/Navbar.tsx
  packages/client/src/widgets/profile-form/ProfileForm.tsx
  packages/client/src/widgets/registration-form/RegistrationForm.tsx
  packages/client/src/widgets/topic/Topic.tsx
  yarn.lock
Labels: to review team, to review praktikum

#15 COD-41: Реализовать одну из игровых механик, описанных в документе с логикой игры
  packages/client/.eslintrc.cjs
  packages/client/src/hooks/useApiCall.ts
  packages/client/src/widgets/game-window/lib/ConsoleController.ts
  packages/client/src/widgets/game-window/lib/GameEngine.ts
Labels: to review team, to review praktikum
