Repository kakbutos/MatchThree, pull requests merged in 2024-02, with the labels that each got.

#27 COD-61: API для форума
  .env.sample
  docker-compose.yml
  packages/client/src/main.tsx
  packages/client/src/store/index.ts
  packages/server/controllers/CommentController.ts
  packages/server/controllers/ReplyController.ts
  packages/server/controllers/TopicController.ts
  packages/server/controllers/init.ts
  packages/server/db.ts
  packages/server/index.ts
  packages/server/models/Comment.ts
  packages/server/models/Reply.ts
  packages/server/models/Topic.ts
  packages/server/package.json
  packages/server/tsconfig.json
  yarn.lock
Labels: done

#31 Добавить API для лидерборда
  packages/client/src/constants/index.ts
  packages/client/src/services/api/leaderboard/leaderboard-api.ts
  packages/client/src/types/leaderboard/leaderboard.ts
  packages/client/src/widgets/game-window/GameWindow.tsx
  packages/client/src/widgets/game-window/TimeBar.tsx
  packages/client/src/widgets/game-window/lib/GameEngine.ts
  packages/client/src/widgets/leaderboard/Leaderboard.tsx
  packages/client/src/widgets/leaderboard/TableRating.tsx
Labels: to review team

#30 Feature/cod 58
  packages/client/src/assets/icons/fullscreen.svg
  packages/client/src/widgets/game-window/GameWindow.tsx
  packages/client/src/widgets/game-window/game-window.module.scss
Labels: to review team, to review praktikum

#33 Добавлен функционал реакции эмодзи на сообщения и ответы на сообщения
  packages/client/src/types/forum/api.ts
  packages/client/src/widgets/comment/Comment.tsx
  packages/client/src/widgets/comment/Reply.tsx
  packages/client/src/widgets/comment/comment.module.scss
  packages/client/src/widgets/reaction-box/EmojiService.ts
  packages/client/src/widgets/reaction-box/ReactionBox.tsx
  packages/client/src/widgets/reaction-box/reaction-box.module.scss
Labels: to review team, to review praktikum

#32 Серверная инфраструктура + фиксы ux/ui багов
  Dockerfile.client
  Dockerfile.server
  docker-compose.yml
  packages/client/src/app/index.tsx
  packages/client/src/constants/index.ts
  packages/client/src/pages/forum/Forum.tsx
  packages/client/src/pages/game/Game.tsx
  packages/client/src/widgets/auth-form/OAuth-button.tsx
  packages/client/src/widgets/end-game/EndGame.tsx
  packages/client/src/widgets/game-window/GameWindow.tsx
  packages/client/src/widgets/game-window/lib/ConsoleController.ts
  packages/client/src/widgets/image-layout/ImageLayout.tsx
  packages/client/src/widgets/leaderboard/TableRating.tsx
  packages/client/src/widgets/main/navbar/Navbar.tsx
  packages/client/src/widgets/profile-form/ProfileForm.tsx
  packages/client/src/widgets/reaction-box/ReactionBox.tsx
  packages/client/src/widgets/start/Start.tsx
  packages/server/db.ts
  packages/server/package.json
  yarn.lock
Labels: done
